[phases.setup]
nixPkgs = ['...', 'php82', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.mbstring']

[phases.install]
cmds = [
  'composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader',
  'mkdir -p storage/framework/{sessions,views,cache}',
  'chmod -R 775 storage bootstrap/cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'

