[build]
builder = "nixpacks"

[build.nixpacksPlan]
providers = ["php"]

[build.nixpacksPlan.phases.setup]
nixPkgs = ["php82", "php82Extensions.mbstring", "php82Extensions.pdo", "php82Extensions.pdo_mysql"]

[build.nixpacksPlan.phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction"
]

[build.nixpacksPlan.phases.build]
cmds = [
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[build.nixpacksPlan.start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"

